packages:
  - "apps/*"
  - "packages/*"

overrides:
  react: 19.1.0
  react-native: 0.81.5

allowBuilds:
  esbuild: false
  mongodb-memory-server: true
  msw: false
  unrs-resolver: false

catalog:
  vitest: ^4.1.2
  "@vitest/coverage-v8": ^4.1.2
