module.exports = {
  semi: true,
  singleQuote: false,
  trailingComma: "all",
  printWidth: 100,
  tabWidth: 2,
  arrowParens: "always",
  importOrder: [
    "^react$",
    "^react-dom",
    "^react-native$",
    "^react-native/",
    "^react-(.*)$",
    "^expo",
    "^@expo/",
    "^@react-navigation/",
    "^@nestjs/",
    "^@belot/(.*)$",
    "^@/components/(.*)$",
    "^@/ui/(.*)$",
    "^@/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
};
