"use client";
import { vars } from "nativewind";

const lightTheme = {
  background: "255 255 255",
  foreground: "10 10 10",
  primary: "23 23 23",
  primaryForeground: "250 250 250",
  secondary: "200 200 200",
  secondaryForeground: "23 23 23",
  muted: "245 245 245",
  mutedForeground: "115 115 115",
  destructive: "231 0 11",
  border: "229 229 229",
  input: "229 229 229",
  ring: "161 161 161",
  phoneScreenBackground: "255 255 255",
  inputField: "187 187 187",
  inputFieldForeground: "0 0 0",
  success: "64 185 70",
  successForeground: "248 248 248",
};

const darkTheme = {
  background: "10 10 10",
  foreground: "250 250 250",
  primary: "229 229 229",
  primaryForeground: "23 23 23",
  secondary: "115 115 115",
  secondaryForeground: "250 250 250",
  muted: "38 38 38",
  mutedForeground: "161 161 161",
  destructive: "255 100 103",
  border: "255 255 255",
  input: "255 255 255",
  ring: "115 115 115",
  phoneScreenBackground: "34 34 34",
  inputField: "134 134 134",
  inputFieldForeground: "255 255 255",
  success: "64 185 70",
  successForeground: "11 11 11",
};

export const PHONE_SCREEN_BACKGROUND = {
  light: `rgb(${lightTheme.phoneScreenBackground})`,
  dark: `rgb(${darkTheme.phoneScreenBackground})`,
} as const;

const buildThemeVars = (theme: typeof lightTheme) =>
  vars({
    "--color-primary-0": theme.primary,
    "--color-primary-50": theme.primary,
    "--color-primary-100": theme.primary,
    "--color-primary-200": theme.primary,
    "--color-primary-300": theme.primary,
    "--color-primary-400": theme.primary,
    "--color-primary-500": theme.primary,
    "--color-primary-600": theme.primary,
    "--color-primary-700": theme.primary,
    "--color-primary-800": theme.primary,
    "--color-primary-900": theme.primary,
    "--color-primary-950": theme.primary,

    "--color-secondary-0": theme.secondary,
    "--color-secondary-50": theme.secondary,
    "--color-secondary-100": theme.secondary,
    "--color-secondary-200": theme.secondary,
    "--color-secondary-300": theme.secondary,
    "--color-secondary-400": theme.secondary,
    "--color-secondary-500": theme.secondary,
    "--color-secondary-600": theme.secondary,
    "--color-secondary-700": theme.secondary,
    "--color-secondary-800": theme.secondary,
    "--color-secondary-900": theme.secondary,
    "--color-secondary-950": theme.secondary,

    "--color-tertiary-50": theme.secondary,
    "--color-tertiary-100": theme.secondary,
    "--color-tertiary-200": theme.secondary,
    "--color-tertiary-300": theme.secondary,
    "--color-tertiary-400": theme.secondary,
    "--color-tertiary-500": theme.secondary,
    "--color-tertiary-600": theme.secondary,
    "--color-tertiary-700": theme.secondary,
    "--color-tertiary-800": theme.secondary,
    "--color-tertiary-900": theme.secondary,
    "--color-tertiary-950": theme.secondary,

    "--color-error-0": theme.destructive,
    "--color-error-50": theme.destructive,
    "--color-error-100": theme.destructive,
    "--color-error-200": theme.destructive,
    "--color-error-300": theme.destructive,
    "--color-error-400": theme.destructive,
    "--color-error-500": theme.destructive,
    "--color-error-600": theme.destructive,
    "--color-error-700": theme.destructive,
    "--color-error-800": theme.destructive,
    "--color-error-900": theme.destructive,
    "--color-error-950": theme.destructive,

    "--color-success-0": theme.success,
    "--color-success-50": theme.success,
    "--color-success-100": theme.success,
    "--color-success-200": theme.success,
    "--color-success-300": theme.success,
    "--color-success-400": theme.success,
    "--color-success-500": theme.success,
    "--color-success-600": theme.success,
    "--color-success-700": theme.success,
    "--color-success-800": theme.success,
    "--color-success-900": theme.success,
    "--color-success-950": theme.success,

    "--color-warning-0": theme.secondary,
    "--color-warning-50": theme.secondary,
    "--color-warning-100": theme.secondary,
    "--color-warning-200": theme.secondary,
    "--color-warning-300": theme.secondary,
    "--color-warning-400": theme.secondary,
    "--color-warning-500": theme.secondary,
    "--color-warning-600": theme.secondary,
    "--color-warning-700": theme.secondary,
    "--color-warning-800": theme.secondary,
    "--color-warning-900": theme.secondary,
    "--color-warning-950": theme.secondary,

    "--color-info-0": theme.ring,
    "--color-info-50": theme.ring,
    "--color-info-100": theme.ring,
    "--color-info-200": theme.ring,
    "--color-info-300": theme.ring,
    "--color-info-400": theme.ring,
    "--color-info-500": theme.ring,
    "--color-info-600": theme.ring,
    "--color-info-700": theme.ring,
    "--color-info-800": theme.ring,
    "--color-info-900": theme.ring,
    "--color-info-950": theme.ring,

    "--color-typography-0": theme.primaryForeground,
    "--color-typography-50": theme.primaryForeground,
    "--color-typography-100": theme.primaryForeground,
    "--color-typography-200": theme.mutedForeground,
    "--color-typography-300": theme.mutedForeground,
    "--color-typography-400": theme.mutedForeground,
    "--color-typography-500": theme.mutedForeground,
    "--color-typography-600": theme.foreground,
    "--color-typography-700": theme.foreground,
    "--color-typography-800": theme.foreground,
    "--color-typography-900": theme.foreground,
    "--color-typography-950": theme.foreground,

    "--color-outline-0": theme.border,
    "--color-outline-50": theme.border,
    "--color-outline-100": theme.border,
    "--color-outline-200": theme.border,
    "--color-outline-300": theme.border,
    "--color-outline-400": theme.ring,
    "--color-outline-500": theme.ring,
    "--color-outline-600": theme.ring,
    "--color-outline-700": theme.ring,
    "--color-outline-800": theme.foreground,
    "--color-outline-900": theme.foreground,
    "--color-outline-950": theme.foreground,

    "--color-background-0": theme.background,
    "--color-background-50": theme.muted,
    "--color-background-100": theme.muted,
    "--color-background-200": theme.border,
    "--color-background-300": theme.input,
    "--color-background-400": theme.ring,
    "--color-background-500": theme.ring,
    "--color-background-600": theme.mutedForeground,
    "--color-background-700": theme.foreground,
    "--color-background-800": theme.foreground,
    "--color-background-900": theme.foreground,
    "--color-background-950": theme.foreground,

    "--color-background-error": theme.destructive,
    "--color-background-warning": theme.muted,
    "--color-background-success": theme.success,
    "--color-background-muted": theme.muted,
    "--color-background-info": theme.muted,

    "--color-indicator-primary": theme.ring,
    "--color-indicator-info": theme.ring,
    "--color-indicator-error": theme.destructive,

    "--color-phone-screen-background": theme.phoneScreenBackground,
    "--color-input-field": theme.inputField,
    "--color-input-field-foreground": theme.inputFieldForeground,
    "--color-success-foreground": theme.successForeground,
  });

export const config = {
  light: buildThemeVars(lightTheme),
  dark: buildThemeVars(darkTheme),
};
